### PR TITLE
Add account creation with certificate to initial setup

### PR DESCRIPTION
**Pull request by intika**
bug2 (the light one) on https://github.com/kriztan/Pix-Art-Messenger/issues/438

### CODE REVIEW

**Comment by kriztan** [comment]
It's not supposed to add a new account from an account view.

**Comment by kriztan** [comment]
Maybe it could be a feature for the WelcomeActivity for initial setup.

**Comment by intika** [comment]
> It's not supposed to add a new account from an account view.

Yes indeed somehow, but...

> Maybe it could be a feature for the WelcomeActivity for initial setup.

...but the `WelcomeActivity` is using `EditAccountActivity` to create a new account (see the code bellow), this is why i added that code there, because there is no other place to add it to, otherwise we would add a much more code to just do the same thing... 

`intent intent = new Intent(WelcomeActivity.this, EditAccountActivity.class);`...

**Comment by kriztan** [comment]
If it is necessary to add much more code, it should be done. 
You can add an EXTRA for an intent to catch this in EditAccountActivity, this would not need as much more code as you think,

**Comment by intika** [comment]
> You can add an EXTRA for an intent... 

Yes true i though you were referring to create a new activity or something else... (to separate completely edition from creation)

Any way i just used the current function/behavior to achieve this as `onCreateOptionsMenu()` from `EditAccountActivity` was already handling account creation and edition by hiding/enabling some menu items (like other functions on that activity because EditAccountActivity was meant for both creation and edition)... 

On the other hand i understand you; Where the function here belong more to the welcome activity... I have a very limited time currently, feel free to close or merge as you please, this PR is just to contribute by highlighting/fixing something that did not work ;)

**Comment by kriztan** [comment]
You should have spent your limited time to implement this in the correct way via WelcomeActivity and EXTRA intent... Feel free to correct the feature and repopen the PR again.

**Pull request closed without merging**
