### PR TITLE
emoji button

### PR DESCRIPTION
**Pull request by sebest06**
Hello, i add a button to add emoji. This button show a emoji keyboard with google compact. This button is very important in the android device with old versions.

In the old versions of Android, other emoji are shown than the ones that will be sent. With this emoji keyboard you see the same thing that will be sent

The emoji keyboard is made by vanniktech.

You can consider this improve for add to the project.

Thanks

pix-art-msj

### CODE REVIEW

**Comment by kriztan** [comment]
Thanks for your work. 
During my fast review I asked me if the additionally implemented libraries could be integrated as is, without coping everything into my source code. This is much easier to update. Another question is why don't you use the already implemented com.android.support:support-emoji library for your emojis? In your current PR the most emojis are duplicated in two different libraries, and this uses much more memory.
Please let us discuss this points.

**Comment by sebest06** [comment]
Hi, the first thing i wanna to say is, i am not an android developer, this "littles improves" are my first tries in the android world.

In my previous message i said, "The emoji keyboard is made by vanniktech." i only integreted the library in this project. (Really i changed some little things in the library and i want vanniktech accept my changes, and "publish" the library in maven). I can only say your observations to vanniktech to update the library. 

But if you think that work is good, and if possible to insert in the project i can work a little more for improve somethings

Thanks!

**Comment by github-tomster** [comment]
please ensure, that the standard **'sytem/font/NotoColorEmoji.ttf'** font can be used.
there are users which love pix-art because of the fact the system NotoColorEmoji.ttf can
be used and that there is no need to embedd some NONCHANGEABLE emoji
hardcoded into the application!

**Comment by github-tomster** [comment]
to complete my above message:
these users are aware that they have to use the correct UNiCODE v11 NotoColorEmoji.ttf ;-)

**Comment by github-tomster** [comment]
please ensure, that the standard 'sytem/font/NotoColorEmoji.ttf' font can be used.
there are users which love pix-art because of the fact the system NotoColorEmoji.ttf can
be used and that there is no need to embedd some NONCHANGEABLE emoji
hardcoded into the application!
these users are also aware that an UNiCODE v11 compatible NotoColorEmoji.ttf is needed!

please dont let the user bare a non-customizable emoji version/style. 
(there are: samsung, apple, google e.t.c.)
and the user should be able to change this! as it is now possible with pix-art!

**Comment by kriztan** [comment]
Pix-Art Messenger can use integrated or system emojis, this can be configured within the settings. I also recommend to use emojis based on this settings instead of using another lilbrary.

**Comment by Echolon** [comment]
@sebest06 any updates on this?

**Comment by kriztan** [comment]
No reaction from developer, so closing this. Feel free to reopen it or send another pull request.

**Pull request closed without merging**
