### PR TITLE
design message border

### PR DESCRIPTION
**Pull request by genofire**
6b7nypq3rg-zr1jquufqfw
45zcfz6grusp3_m4pvjutg

### CODE REVIEW

**Comment by genofire** [comment]
A new try, to be a little bit more elegant

**Comment by kriztan** [comment]
The light variant with borders, the dark one without?

**Comment by Kelvino9** [comment]
Light theme without borders would look even more modern. The borders gives the chat bubbles a pre material design.

**Comment by genofire** [comment]
I wish i could remove borders everywhere - but light sent/blue chatbubbles looks really strange without
ngtdpuzwsssfpv7rabxmew

**Comment by Kelvino9** [comment]
Try to set the borders only a few values apart from the same color of the bubbles so it is not as obvious as before, but still visible.

**Comment by genofire** [comment]
okay i define new colors ;(

**Comment by genofire** [comment]
Change to official [Material Colors](https://www.materialui.co/colors): 
xx-487qktz2mj0aawan38g_7221f35c54d34079be7246a2cf483be636a4d482
1jqtfjgdsdscvofkh3rjhg_94661008f88e03f341d5fcc02598ef9b1f619516

**Pull request merged**
