### PR TITLE
New Feature: Delete conversation message

### PR DESCRIPTION
**Pull request by acw81**
New feature added which enables the possibilty to delete a single message from the local conversation/client.

### CODE REVIEW

**Comment by kriztan** [comment]
Thanks for your contribution. Could you please implement my hints and rebase all commits to one commit?

**Comment by kriztan** [comment]
integrated with 4f612fc9bc50e8665c11cab59f502ace854a4a9f

**Comment by kolAflash** [comment]
Is this feature already present in version 2.1.2?

A friend just send me a message with a password and asked me to delete it after usage. But I can't find out how to do that, without deleting the whole chat history.

**Comment by kriztan** [comment]
It's currently not implemented, because of negative side effects.

**Comment by kriztan** [comment]
I've implemented a working method to delete (hide) messages from chats.

**Comment by Ppjet6** [comment]
Hi there,

We (poezio) just got ask by a user what was the XEP for _message deletion_, and if it was possible to implement it, as Pix Art does. As developers we know this XEP doesn't exist, (and probably never will due to technical limitations).

I vote to remove the feature entirely. Having an option in the context menu of a message that says "Delete" can only be misguiding.

If you really want the feature, please be careful about the terminology, and make it clear that this only affects the local state, and that any recipient will still be able to see.

**Comment by acw81** [comment]
Hello Maxime,

you will get attached hint if you delete a Message.



Am Di., 13. Nov. 2018, 12:46 hat Maxime Buquet <notifications@github.com>
geschrieben:

**Pull request closed without merging**
