### PR TITLE
Networkstack: let OS decide IPv4 or IPv6

### PR DESCRIPTION
**Pull request by genofire**

### CODE REVIEW

**Comment by Echolon** [comment]
@genofire thank you for working on this!

**Comment by kriztan** [comment]
I've checked the code against you last PR with this feature and can't find any major differences. In your last PR some people had problems connecting because their providers have an IPv4 and IPv6 address, but the XMPP server is just listening on the IPv4 address. Is there a chance to fall back to the IPv4 and vice versa?

**Comment by genofire** [comment]
Yes, ATM it is just the updated code with cleanup (and a bugfix) and no happy eyeball implementation.
I did not found any library or if it android is able to make it internal.

(thats the reason why i let this PR in WIP)

**Comment by genofire** [comment]
Found a Happy Eyeball implementation by the RIPE ;)
https://github.com/RIPE-NCC/rpki-validator-3/blob/master/rpki-validator/src/main/java/net/ripe/rpki/validator3/util/HappyEyeballsResolver.java

It will take some time to reimplement and test it in "Conv6ersation for Sum7" and later here.

**Comment by genofire** [comment]
https://dev.sum7.eu/sum7/Conversations/commit/e3640670a8184c0a335a18802a0bc5b6c79f5a0f

Should be easy to reimplement without the **let OS decide IPv4 or IPv6** commit.
Importend parts are remove compare part with IP-Adress Family (without happy eyeball would not be fair between protocols).
To prefer IPv6 in selection of A should be after AAAA (if both/dualstack works correct then it will prefer IPv6, that is recommended).

**Comment by genofire** [comment]
So PR #411 is there - now it is your choice

**Pull request closed without merging**
