### PR TITLE
Networkstack - let OS decide IPv4 or IPv6

### LINKED ISSUE #207: Use IPv6
#### General information

* **Version:** 2.0.2
* **Device:** FP2
* **Android Version:** Android 7.1.2 LineageOS 14.1

#### Steps to reproduce
Connect to a dual-stack xmpp hoster.

#### Expected result
Connection with IPv6

#### Actual result

Connected with IPv4

#### Debug output

Please post the output of adb logcat. The log should begin with the start of Pix-Art Messenger and include all the
steps it takes to reproduce the problem.

````
adb -d logcat -v time | FINDSTR Pix-Art > logcat.txt
````

### PR DESCRIPTION
**Pull request by genofire**
Use networkstack of OS and let him decide over IPv4 or IPv6

Fix #207

### CODE REVIEW

**Comment by genofire** [comment]
@kriztan any opinion? I am running this patch at my testing Client: https://git.sum7.eu/sum7/Conversations/

**Comment by genofire** [comment]
Any updates? @kriztan

**Comment by genofire** [comment]
This patch runs now for a while in F-Droid:
https://f-droid.org/packages/eu.sum7.conversations

The drop of own implemetation of DNS-Server selection is new and should also solve:
https://github.com/siacs/Conversations/issues/3465

**Comment by kriztan** [comment]
Could you please resolve the conflicts? I'd like to merge this into the upcoming release. Thanks

**Comment by genofire** [comment]
Done + remove dns resolver cache

**Pull request merged**
